const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='cps-hub-workspace-v2';
const groups={Sessions:['Morning Report','CPS Academy VMRs','Special VMRs','Student Forum','Leader of the Week'],People:['Members','OrgStructure','CRC'],Production:['Podcast Episodes','Schema review'],Research:['Research @CPSolvers','Conferences'],Links:['Important links']};
const descriptions={'Morning Report':'The session team, sign-ups and teaching support in one place.','CPS Academy VMRs':'Explore the Academy’s learning archive. Find a topic, facilitator or recording.','CRC':'Follow presenters, mentoring assignments and case progress.','Members':'Find Academy members, sponsors and social handles.','OrgStructure':'Responsibilities and teams, as recorded in the workbook.','Research @CPSolvers':'Find collaborators by research skills and availability.','Podcast Episodes':'Coordinate ownership and editing. The workbook target is readiness two days before release.','Schema review':'Coordinate video, infographic and review assignments. Friday review → Monday upload.','Important links':'Your recurring Academy resources, ready to open.'};
const titles={'Morning Report':'Date','CPS Academy VMRs':'Session title','Members':'Name','OrgStructure':'Team / responsibility','CRC':'Presenter','Research @CPSolvers':'Name','Podcast Episodes':'Episode','Schema review':'Schema','Conferences':'Congress','Important links':'Resource','Leader of the Week':'Member','Special VMRs':'Details','Student Forum':'Topic'};
const facets={'Morning Report':'Type','CPS Academy VMRs':'Facilitator','Members':'Country','CRC':'Status','Research @CPSolvers':'Availability','Schema review':'Status','Podcast Episodes':'Audio editor','OrgStructure':'Role','Special VMRs':'Type'};
let db={},tab='Home',query='',filter='All',facet='',sort='source',page=0,mode='cards',selected=null,editingTab='',workspace={edits:{},added:[],favorites:[],history:[]},storageIssue=false;
try{const saved=JSON.parse(localStorage.getItem(KEY)||'null');if(saved&&saved.edits&&Array.isArray(saved.added)&&Array.isArray(saved.favorites)&&Array.isArray(saved.history))workspace=saved;else workspace.edits=JSON.parse(localStorage.getItem('cps-workbook-edits-v1')||'{}')||{}}catch{storageIssue=true}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),3500)}
function save(next){try{localStorage.setItem(KEY,JSON.stringify(next));workspace=next;return true}catch{toast('Could not save. Export a backup before closing this browser.');return false}}
function mutate(fn){const next=structuredClone(workspace);fn(next);return save(next)}
function records(t=tab){return [...(db[t]?.records||[]),...workspace.added.filter(r=>r.tab===t)].map(r=>({...r,fields:{...r.fields,...workspace.edits[r.id]}}))}
function title(r,t=tab){return r.fields[titles[t]]||r.fields.Topic||r.fields.Type||'Untitled record'}
function source(r){return r.row?`${r.source} · row ${r.row}`:'Created in this browser'}
function dateValue(r){return r.fields.Date||r.fields['Date / time (source)']||r.fields['Release date']||r.fields.Start||''}
const iso=v=>/^\d{4}-\d{2}-\d{2}$/.test(v);
const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'Africa/Johannesburg'});
function urls(r,key){return [...new Set([r.links?.[key],...(String(r.fields[key]||'').match(/https?:\/\/[^\s<>]+/g)||[])].filter(u=>u&&/^https?:\/\//i.test(u)))]}
function anchor(url,label){return `<a class="button secondary small" href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(label)} ↗</a>`}
function chip(s,kind=''){return `<span class="tag ${kind}">${esc(s)}</span>`}
function navigate(t){tab=t;query='';filter=t==='Morning Report'?'Upcoming':'All';facet='';sort='source';page=0;$('#global-search').value='';location.hash=encodeURIComponent(t);render();window.scrollTo(0,0)}
function nav(){const entries=['Home',...Object.keys(groups),'Workspace'];const current=Object.keys(groups).find(g=>groups[g].includes(tab))||tab;$('#desktop-nav').innerHTML=entries.map(g=>`<button class="nav-button ${current===g?'active':''}" data-nav="${g}">${g}</button>`).join('');$('#mobile-nav').innerHTML=entries.map(g=>`<button class="nav-button ${current===g?'active':''}" data-nav="${g}">${g}</button>`).join('');document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>navigate(groups[b.dataset.nav]?.[0]||b.dataset.nav));$('#new-item-button').textContent=tab==='Home'||tab==='Workspace'?'+ New session':'+ Add record';}
function header(t,sub){return `<div class="page-heading"><div><p class="eyebrow">CPS Academy · private workspace</p><h1>${esc(t)}</h1><p>${esc(sub)}</p></div></div>`}
function banner(){return `<div class="snapshot-note"><span class="snapshot-dot"></span><span>Workbook snapshot · changes saved on this device · <button class="text-button" data-go="Workspace">Backups & activity</button></span></div>`}
function actionButtons(r,t){return `<button class="button primary small" data-open="${esc(r.id)}" data-area="${esc(t)}">${t==='Morning Report'?'Staff session':'Open details'}</button><button class="icon-button star ${workspace.favorites.includes(r.id)?'is-starred':''}" aria-label="${workspace.favorites.includes(r.id)?'Unpin':'Pin'} record" data-star="${esc(r.id)}">${workspace.favorites.includes(r.id)?'★':'☆'}</button>`}
function card(r,t=tab){const f=r.fields;let body='',tag='';
 if(t==='Morning Report'){tag=f.Type||'Morning Report';body=`<p class="muted">${esc(f['Pacific time (source)']||'Time TBD')} Pacific · ${esc(f['Eastern time (source)']||'TBD')} Eastern (source)</p><div class="assignments"><div><small>Facilitator</small><strong>${esc(f.Facilitator||'Unassigned')}</strong></div><div><small>Presenter</small><strong>${esc(f.Presenter||(f['Scribe / teaching points sign-ups']||'').match(/Case Presenter:\s*([^\n]+)/i)?.[1]||'Not entered')}</strong></div></div><p class="assignment-note">${esc(f['Scribe / teaching points sign-ups']||'Scribe / teaching points not assigned')}</p>`}
 else if(t==='CPS Academy VMRs'){tag=f.Topic||'Academy learning';body=`<p>${esc(f.Facilitator||'Facilitator not entered')}</p><p class="muted">${esc(f['Date / time (source)']||'Date not entered')}</p><div class="card-links">${urls(r,'Recording').map(u=>anchor(u,'Watch recording')).join('')}${urls(r,'Bonus learning').map(u=>anchor(u,'Bonus learning')).join('')}</div>`}
 else if(t==='Members'){tag=f.Country||'Country not entered';body=`<p>${esc(f.Subspecialty||f.Location||'Academy member')}</p><p class="muted">Sponsor: ${esc(f.Sponsor||'Not entered')}</p><p>${esc(f['Social handles']||'No social handle entered')}</p>`}
 else if(t==='Research @CPSolvers'){tag=f.Availability||'Availability not entered';body=`<div class="person-meta">${['Research writing','Data analytics','Cross-sectional studies','Systematic reviews','Qualitative studies','Case reports'].filter(k=>f[k]==='Yes').map(k=>chip(k)).join('')||'No skills entered'}</div>`}
 else if(t==='Important links'){tag='Academy resource';body=`<div class="card-links">${urls(r,'Link').map(u=>anchor(u,'Open resource')).join('')||'<p class="muted">No usable link in source. Open details to add one.</p>'}</div>`}
 else{tag=f.Status||f.Role||f.Type||t;const fields=db[t].columns.filter(c=>c!==titles[t]&&!/email|contact|link|meeting|remarks/i.test(c)).slice(0,3);body=fields.map(k=>`<p class="card-line"><small>${esc(k)}</small><span>${esc(f[k]||'Not entered')}</span></p>`).join('')}
 return `<article class="hub-card">${chip(tag)}<h2>${esc(title(r,t))}</h2>${body}<div class="record-markers">${r.flags.length?chip('Verify source details','review-chip'):''}${workspace.edits[r.id]?chip('Local changes','local-chip'):''}</div><footer><div class="card-actions">${actionButtons(r,t)}</div><small class="muted">${esc(source(r))}</small></footer></article>`}
function home(){const next=records('Morning Report').filter(r=>iso(dateValue(r))&&dateValue(r)>=today()).sort((a,b)=>dateValue(a).localeCompare(dateValue(b))).slice(0,3);const pinned=Object.keys(db).flatMap(t=>records(t).filter(r=>workspace.favorites.includes(r.id)).map(r=>({r,t})));$('#page').innerHTML=header('Your Academy, at a glance','Find the next session, return to useful records and keep work moving.')+banner()+`<section class="hero"><div class="hero-copy"><p class="eyebrow">The daily workflow</p><h2>Good teaching starts with a ready team.</h2><p>Open the staffing schedule to coordinate facilitators, presenters, active participants and teaching support.</p><div class="hero-actions"><button class="button primary" data-go="Morning Report">Open staffing schedule</button><button class="button secondary" data-go="CPS Academy VMRs">Explore the archive</button></div></div><div class="hero-meta"><strong>${records('CPS Academy VMRs').length} archive records</strong><strong>${records('Members').length} members in directory</strong><span>Counts reflect the uploaded workbook, not live activity.</span></div></section><div class="dashboard-heading"><h2>Upcoming in the workbook</h2><button class="text-button" data-go="Morning Report">View schedule →</button></div><section class="hub-grid">${next.map(r=>card(r,'Morning Report')).join('')||'<div class="empty-state">No future dated sessions in this snapshot.</div>'}</section><div class="dashboard-heading"><h2>Pinned for quick access</h2><span class="muted">Use ☆ on any record</span></div><section class="hub-grid">${pinned.slice(0,9).map(({r,t})=>card(r,t)).join('')||'<div class="empty-state panel">Pin a session, member or resource to keep it here.</div>'}</section>`;}
function filtered(){let rr=records().filter(r=>Object.values(r.fields).join(' ').toLowerCase().includes(query.toLowerCase()));if(facet)rr=rr.filter(r=>r.fields[facets[tab]]===facet);if(filter==='Needs review')rr=rr.filter(r=>r.flags.length);if(filter==='Local edits')rr=rr.filter(r=>workspace.edits[r.id]||r.id.startsWith('local:'));if(filter==='Pinned')rr=rr.filter(r=>workspace.favorites.includes(r.id));if(filter==='Upcoming')rr=rr.filter(r=>iso(dateValue(r))&&dateValue(r)>=today());if(filter==='Has recording')rr=rr.filter(r=>urls(r,'Recording').length);if(filter==='Missing facilitator')rr=rr.filter(r=>!r.fields.Facilitator||/tbd/i.test(r.fields.Facilitator));if(sort==='az')rr.sort((a,b)=>title(a).localeCompare(title(b)));else if(filter==='Upcoming')rr.sort((a,b)=>dateValue(a).localeCompare(dateValue(b)));else if(sort==='date')rr.sort((a,b)=>{const x=dateValue(a),y=dateValue(b);return iso(x)&&iso(y)?y.localeCompare(x):iso(x)?-1:iso(y)?1:0});return rr}
function listing(){let rr=filtered();page=Math.min(page,Math.max(0,Math.ceil(rr.length/12)-1));const current=rr.slice(page*12,page*12+12),field=facets[tab],options=field?[...new Set(records().map(r=>r.fields[field]).filter(Boolean))].sort():[];const filters=['All',...(tab==='Morning Report'?['Upcoming','Missing facilitator']:[]),...(db[tab].columns.includes('Recording')?['Has recording']:[]),'Pinned','Needs review','Local edits'];$('#page').innerHTML=header(tab,descriptions[tab]||'Programme records, assignments and source details.')+banner()+`<div class="toolbar area-tabs">${groups[Object.keys(groups).find(g=>groups[g].includes(tab))].map(t=>`<button class="button ${t===tab?'primary':'secondary'} small" data-go="${esc(t)}">${esc(t)}</button>`).join('')}</div><div class="filter-bar"><label>Show<select class="select" id="filter">${filters.map(f=>`<option ${f===filter?'selected':''}>${f}</option>`).join('')}</select></label>${field?`<label>${esc(field)}<select class="select" id="facet"><option value="">All</option>${options.map(v=>`<option value="${esc(v)}" ${v===facet?'selected':''}>${esc(v)}</option>`).join('')}</select></label>`:''}<label>Order<select class="select" id="sort"><option value="source">Workbook order</option><option value="az" ${sort==='az'?'selected':''}>Title A–Z</option><option value="date" ${sort==='date'?'selected':''}>Newest exact dates</option></select></label><button class="button secondary" id="clear">Clear filters</button><button class="button secondary" id="view">${mode==='cards'?'Table view':'Card view'}</button></div><p class="muted results-count">${rr.length} matches · ${records().length} records${sort==='date'?' · Unresolved dates follow exact dates':''}</p>${rr.length?(mode==='cards'?`<section class="hub-grid">${current.map(r=>card(r)).join('')}</section>`:table(current)):'<section class="empty-state panel"><h2>No matching records</h2><p>Clear the filters or try a broader search.</p></section>'}<div class="toolbar pagination"><button class="button secondary" id="prev" ${page===0?'disabled':''}>Previous</button><span>Page ${page+1} of ${Math.max(1,Math.ceil(rr.length/12))}</span><button class="button secondary" id="next" ${(page+1)*12>=rr.length?'disabled':''}>Next</button></div>`;$('#filter').onchange=e=>{filter=e.target.value;page=0;render()};if($('#facet'))$('#facet').onchange=e=>{facet=e.target.value;page=0;render()};$('#sort').onchange=e=>{sort=e.target.value;render()};$('#clear').onclick=()=>{query='';filter='All';facet='';sort='source';page=0;$('#global-search').value='';render()};$('#view').onclick=()=>{mode=mode==='cards'?'table':'cards';render()};$('#prev').onclick=()=>{page--;render();window.scrollTo(0,0)};$('#next').onclick=()=>{page++;render();window.scrollTo(0,0)};}
function table(rr){const cols=[titles[tab],...db[tab].columns.filter(c=>c!==titles[tab])].slice(0,4);return `<section class="panel table-panel"><table class="data-table"><thead><tr>${cols.map(c=>`<th>${esc(c)}</th>`).join('')}<th>Action</th></tr></thead><tbody>${rr.map(r=>`<tr>${cols.map(c=>`<td data-label="${esc(c)}">${esc(r.fields[c]||'—')}</td>`).join('')}<td>${actionButtons(r,tab)}</td></tr>`).join('')}</tbody></table></section>`}
function workspaceView(){$('#page').innerHTML=header('Workspace','Keep a portable backup and review your local activity.')+banner()+`<section class="integration-grid"><article class="panel integration-card"><h2>Your changes, safely portable</h2><p>Changes are stored in this browser. Export a backup before switching devices or clearing browser data. Import merges a backup, with incoming values taking priority for the same record.</p><div class="toolbar"><button class="button primary" id="export">Download backup</button><label class="button secondary">Import backup<input type="file" id="import" accept="application/json" hidden></label></div><p class="muted">${Object.keys(workspace.edits).length} edited records · ${workspace.added.length} new records · ${workspace.favorites.length} pins</p></article><article class="panel integration-card"><h2>Connection status</h2><p>This is a copy of the uploaded workbook. No live Google Sheets connection or shared saving is enabled.</p><p>Next integration phase: stable record IDs, shared storage, then permissioned read-only Sheets sync. Source row references are retained for review.</p></article></section><div class="dashboard-heading"><h2>Recent local activity</h2></div><section class="panel activity-list">${workspace.history.slice(0,30).map(h=>`<div><strong>${esc(h.action)} · ${esc(h.title)}</strong><small>${esc(h.tab)} · ${esc(new Date(h.at).toLocaleString())}</small></div>`).join('')||'<div class="empty-state">Your saved changes will appear here.</div>'}</section>`;$('#export').onclick=exportBackup;$('#import').onchange=importBackup;}
function render(){nav();if(tab==='Home')home();else if(tab==='Workspace')workspaceView();else listing();document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>navigate(b.dataset.go));document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openRecord(b.dataset.open,b.dataset.area));document.querySelectorAll('[data-star]').forEach(b=>b.onclick=()=>{if(mutate(w=>{const id=b.dataset.star;w.favorites=w.favorites.includes(id)?w.favorites.filter(x=>x!==id):[...w.favorites,id]}))render()});$('#global-search').placeholder=tab==='Home'?'Search all Academy records…':`Search ${tab.toLowerCase()}…`;}
function openRecord(id,t){editingTab=t;selected=records(t).find(r=>r.id===id);editDialog(false)}
function createRecord(){editingTab=db[tab]?tab:'Morning Report';selected={id:'local:'+crypto.randomUUID(),tab:editingTab,source:'Local draft',row:null,fields:Object.fromEntries(db[editingTab].columns.map(k=>[k,''])),links:{},flags:[]};editDialog(true)}
function editDialog(isNew){const r=selected;$('#dialog-eyebrow').textContent=isNew?'New '+editingTab:source(r);$('#dialog-title').textContent=isNew?'Create a record':title(r,editingTab);$('#dialog-content').innerHTML=`<p class="form-note">Saved on this device. No changes are sent to the live workbook.</p>${r.flags.length?`<details class="review-details"><summary>${r.flags.length} source details to verify</summary>${r.flags.map(f=>`<p>${esc(f)}</p>`).join('')}</details>`:''}<div class="record-form">${db[editingTab].columns.map(c=>`<label class="record-field">${esc(c)}${c===titles[editingTab]?' *':''}<textarea data-field="${esc(c)}" ${c===titles[editingTab]?'required':''} rows="${/notes|remarks|meeting|sign-ups/i.test(c)?3:2}">${esc(r.fields[c])}</textarea>${urls(r,c).map(u=>anchor(u,'Open '+c)).join('')}</label>`).join('')}</div>${!isNew?`<button type="button" class="text-button" id="restore-record">${r.id.startsWith('local:')?'Remove this local draft':'Restore original workbook values'}</button><div id="restore-confirm"></div>`:''}`;$('#dialog-primary').textContent=isNew?'Create local record':'Save changes';$('#dialog-primary').dataset.isNew=String(isNew);if($('#restore-record'))$('#restore-record').onclick=()=>{$('#restore-confirm').innerHTML='<p>This discards this record’s local changes.</p><button type="button" class="button secondary" id="confirm-restore">Confirm restore / removal</button>';$('#confirm-restore').onclick=()=>{if(mutate(w=>{delete w.edits[r.id];if(r.id.startsWith('local:')){w.added=w.added.filter(a=>a.id!==r.id);w.favorites=w.favorites.filter(id=>id!==r.id)}log(w,'Restored / removed',r,editingTab)})){$('#detail-dialog').close();render();toast('Local record restored or removed')}}};$('#detail-dialog').showModal()}
function log(w,action,r,t){w.history.unshift({action,title:title(r,t),tab:t,at:new Date().toISOString()});w.history=w.history.slice(0,100)}
$('#dialog-primary').onclick=e=>{e.preventDefault();const form=$('#detail-dialog form');if(!form.reportValidity())return;const fields={};$('#dialog-content').querySelectorAll('[data-field]').forEach(el=>fields[el.dataset.field]=el.value.trim());if(!fields[titles[editingTab]]){toast('Please enter the required title or name.');return}const isNew=e.currentTarget.dataset.isNew==='true',r={...selected,fields};if(mutate(w=>{if(isNew)w.added.push(r);else w.edits[r.id]=fields;log(w,isNew?'Created':'Updated',r,editingTab)})){$('#detail-dialog').close();render();toast('Saved on this device')}};
function exportBackup(){const blob=new Blob([JSON.stringify({format:'cps-hub-backup-v2',snapshot:'workbook-2026-09-06',exported:new Date().toISOString(),...workspace},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='cps-hub-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('Backup downloaded')}
async function importBackup(e){try{const file=e.target.files[0];if(!file)return;if(file.size>10000000)throw Error('Backup exceeds 10 MB');const b=JSON.parse(await file.text());if(b.format!=='cps-hub-backup-v2'||b.snapshot!=='workbook-2026-09-06'||!Array.isArray(b.added)||!Array.isArray(b.favorites)||!b.edits||typeof b.edits!=='object')throw Error('Unsupported backup format');const known=new Map(Object.entries(db).flatMap(([t,v])=>v.records.map(r=>[r.id,t])));workspace.added.forEach(r=>known.set(r.id,r.tab));const added=b.added.map(r=>{if(!r.id?.startsWith('local:')||!db[r.tab]||!r.fields)throw Error('Invalid draft');known.set(r.id,r.tab);return {...r,source:'Local draft',row:null,flags:[],links:{}}});for(const r of added)validateFields(r.fields,r.tab);for(const [id,fields] of Object.entries(b.edits)){if(!known.has(id))throw Error('Record is not in this snapshot');validateFields(fields,known.get(id))}if(!b.favorites.every(id=>typeof id==='string'&&known.has(id)))throw Error('Invalid pin');if(mutate(w=>{w.edits={...w.edits,...b.edits};const map=new Map(w.added.map(r=>[r.id,r]));added.forEach(r=>map.set(r.id,r));w.added=[...map.values()];w.favorites=[...new Set([...w.favorites,...b.favorites])];w.history.unshift({action:'Imported backup',title:file.name,tab:'Workspace',at:new Date().toISOString()});w.history=w.history.slice(0,100)})){render();toast('Backup imported')}}catch(error){toast('Import failed: '+error.message)}}
function validateFields(fields,t){if(!fields||Array.isArray(fields)||typeof fields!=='object')throw Error('Invalid fields');for(const [k,v] of Object.entries(fields))if(!db[t].columns.includes(k)||typeof v!=='string'||v.length>50000)throw Error('Invalid record field')}
function globalResults(){const q=query.toLowerCase();const found=Object.keys(db).flatMap(t=>records(t).filter(r=>Object.values(r.fields).join(' ').toLowerCase().includes(q)).map(r=>({r,t})));$('#page').innerHTML=header('Search the Academy',`${found.length} matches across all workbook areas. Showing the first 24.`)+`<section class="hub-grid">${found.slice(0,24).map(({r,t})=>card(r,t)).join('')||'<div class="empty-state">No matches found.</div>'}</section>`;document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openRecord(b.dataset.open,b.dataset.area));document.querySelectorAll('[data-star]').forEach(b=>b.onclick=()=>{if(mutate(w=>{w.favorites=w.favorites.includes(b.dataset.star)?w.favorites.filter(id=>id!==b.dataset.star):[...w.favorites,b.dataset.star]}))globalResults()})}
$('#global-search').oninput=e=>{query=e.target.value;page=0;if(tab==='Home'&&query.trim())globalResults();else render()};$('#new-item-button').onclick=createRecord;
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='k'){e.preventDefault();$('#global-search').focus()}});
$('.sync-card').onclick=()=>navigate('Workspace');$('.sync-card strong').textContent='Workbook snapshot';$('.sync-card small').textContent='Local changes · no live sync';$('.notification-button')?.remove();$('.profile .icon-button')?.remove();
window.addEventListener('hashchange',()=>{const t=decodeURIComponent(location.hash.slice(1));if(t!==tab&&(db[t]||['Home','Workspace'].includes(t)))navigate(t)});
fetch('workbook.json').then(r=>{if(!r.ok)throw Error();return r.json()}).then(data=>{db=data;const hash=decodeURIComponent(location.hash.slice(1));if(db[hash]||['Home','Workspace'].includes(hash))tab=hash;filter=tab==='Morning Report'?'Upcoming':'All';render();if(storageIssue)toast('Browser storage could not be read. Export changes before leaving.')}).catch(()=>{$('#page').innerHTML='<div class="empty-state"><h1>Could not load the workbook</h1><p>Please reload this page.</p></div>'});
