const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let db={},tab='Morning Report',query='',filter='All',offset=0,selected=null;
let edits;try{edits=JSON.parse(localStorage.getItem('cps-workbook-edits-v1')||'{}')}catch{edits={}}
const groups={Sessions:['Morning Report','CPS Academy VMRs','Special VMRs','Student Forum','Leader of the Week'],People:['Members','OrgStructure','CRC'],Production:['Podcast Episodes','Schema review'],Research:['Research @CPSolvers','Conferences'],Links:['Important links']};
const notes={'Morning Report':'Staff sessions: facilitator, presenter, active participants, chat support, scribe and teaching points. Times are preserved as entered; timezone conversion has not been assumed.','CPS Academy VMRs':'Search the Academy learning archive by topic, facilitator or session title. Public flags are source metadata; they do not change this site’s privacy.','Podcast Episodes':'Workbook target: ready for upload two days before release. Editor → reviewer → feedback is the documented handoff.','Schema review':'Separate video and infographic ownership. Friday review, Monday upload is the documented cadence. Flagged rows retain the original values.','Research @CPSolvers':'Find collaborators by research skills and availability. This is a member registry.'};
function rows(){return db[tab].records.map(r=>({...r,fields:{...r.fields,...edits[r.id]}}))}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2800)}
function persist(){localStorage.setItem('cps-workbook-edits-v1',JSON.stringify(edits))}
function navigate(t){tab=t;query='';filter='All';offset=0;$('#global-search').value='';history.replaceState(null,'','#'+encodeURIComponent(t));render()}
function group(){return Object.keys(groups).find(g=>groups[g].includes(tab))}
function linkText(value,target){const text=String(value||'');const urls=[...new Set([target,...(text.match(/https?:\/\/[^\s<>]+/g)||[])].filter(Boolean))];return `<span>${esc(text||'—')}</span>`+urls.filter(u=>/^https?:\/\//i.test(u)).map(u=>` <a class="text-button" href="${esc(u)}" target="_blank" rel="noopener noreferrer">Open ↗</a>`).join('')}
function render(){
 $('#desktop-nav').innerHTML=Object.keys(groups).map(g=>`<button class="nav-button ${group()===g?'active':''}" data-group="${g}">${g}</button>`).join('');
 $('#mobile-nav').innerHTML=$('#desktop-nav').innerHTML;
 document.querySelectorAll('[data-group]').forEach(b=>b.onclick=()=>navigate(groups[b.dataset.group][0]));
 let rr=rows().filter(r=>JSON.stringify(r.fields).toLowerCase().includes(query.toLowerCase()));
 if(filter==='Needs review')rr=rr.filter(r=>r.flags.length);
 if(filter==='Local edits')rr=rr.filter(r=>edits[r.id]);
 if(filter==='Upcoming')rr=rr.filter(r=>/^\d{4}-\d{2}-\d{2}$/.test(r.fields.Date||'')&&r.fields.Date>=new Date().toISOString().slice(0,10));
 if(tab==='Morning Report')rr.sort((a,b)=>filter==='Upcoming'?String(a.fields.Date).localeCompare(String(b.fields.Date)):String(b.fields.Date).localeCompare(String(a.fields.Date)));
 const cols=({'Morning Report':['Date','Type','Facilitator','Presenter'],'CPS Academy VMRs':['Session title','Topic','Facilitator','Date / time (source)'],'Members':['Name','Country','Social handles'],'Research @CPSolvers':['Name','Availability','Research writing','Data analytics']})[tab]||db[tab].columns.slice(0,5);
 $('#page').innerHTML=`<div class="page-heading"><div><p class="eyebrow">Workbook snapshot · private workspace</p><h1>${esc(tab)}</h1><p>${esc(notes[tab]||'Imported records with original fields, links and source references.')}</p></div></div><div class="source-banner"><div><strong>Uploaded workbook snapshot · ${db[tab].records.length} records</strong><span>Not synced with Google Sheets. Edits are saved in this browser only. Source values and uncertain dates are preserved.</span></div><button class="button secondary" id="export">Export local changes</button></div><div class="toolbar"><div class="segmented">${groups[group()].map(t=>`<button data-tab="${esc(t)}" class="${tab===t?'active':''}">${esc(t)}</button>`).join('')}</div></div><div class="toolbar"><select id="filter" class="select" aria-label="Filter records">${['All',...(tab==='Morning Report'?['Upcoming']:[]),'Needs review','Local edits'].map(f=>`<option ${filter===f?'selected':''}>${f}</option>`).join('')}</select><span>${rr.length} matching records</span></div><section class="panel table-panel"><table class="data-table"><thead><tr>${cols.map(c=>`<th>${esc(c)}</th>`).join('')}<th>Details</th></tr></thead><tbody>${rr.slice(offset,offset+30).map(r=>`<tr>${cols.map(c=>`<td data-label="${esc(c)}">${esc(r.fields[c]||'—')}</td>`).join('')}<td><button class="button secondary" data-id="${esc(r.id)}">Open${r.flags.length?' ⚠':''}${edits[r.id]?' •':''}</button><small class="muted source-ref">${esc(r.source)} · row ${r.row}</small></td></tr>`).join('')}</tbody></table>${rr.length?'':'<div class="empty-state">No matching records. Try another search or filter.</div>'}</section><div class="toolbar pagination"><button class="button secondary" id="prev" ${offset===0?'disabled':''}>Previous</button><span>${rr.length?offset+1:0}–${Math.min(offset+30,rr.length)} of ${rr.length}</span><button class="button secondary" id="next" ${offset+30>=rr.length?'disabled':''}>Next</button></div>`;
 document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>navigate(b.dataset.tab));
 document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>openRecord(b.dataset.id));
 $('#filter').onchange=e=>{filter=e.target.value;offset=0;render()};$('#prev').onclick=()=>{offset=Math.max(0,offset-30);render()};$('#next').onclick=()=>{offset+=30;render()};
 $('#export').onclick=()=>{const blob=new Blob([JSON.stringify({source:'Uploaded CPSolvers workbook',exported:new Date().toISOString(),changes:edits},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='cps-local-changes.json';a.click();URL.revokeObjectURL(a.href)};
}
function openRecord(id){selected=rows().find(r=>r.id===id);const r=selected;$('#dialog-eyebrow').textContent=`${r.source} · row ${r.row}`;$('#dialog-title').textContent=r.fields['Session title']||r.fields.Name||r.fields.Schema||r.fields.Episode||r.fields.Date||Object.values(r.fields)[0];$('#dialog-content').innerHTML=`${r.flags.map(f=>`<p class="source-banner">${esc(f)}</p>`).join('')}<p class="form-note">Edit this browser’s copy. Original workbook and Google Sheets stay unchanged.</p>${db[tab].columns.map((c,i)=>`<label class="record-field">${esc(c)}<textarea data-field="${esc(c)}" rows="2">${esc(r.fields[c])}</textarea></label>${r.links[c]||/https?:/.test(r.fields[c])?`<div class="record-links">${linkText('',r.links[c])}${linkText(r.fields[c])}</div>`:''}`).join('')}`;$('#dialog-primary').textContent='Save local changes';$('#detail-dialog').showModal()}
$('#dialog-primary').onclick=e=>{e.preventDefault();const changed={};$('#dialog-content').querySelectorAll('[data-field]').forEach(el=>changed[el.dataset.field]=el.value);try{const previous=edits;edits={...edits,[selected.id]:changed};try{persist()}catch(error){edits=previous;throw error;}$('#detail-dialog').close();render();toast('Local changes saved')}catch{toast('Unable to save: browser storage unavailable')}};
$('#global-search').oninput=e=>{query=e.target.value;offset=0;render()};
$('#new-item-button').textContent='Help';$('#new-item-button').onclick=()=>toast('Open a record to edit assignments, notes or status. Export local changes for review.');
$('.sync-card').onclick=()=>toast('Snapshot only. A later API adapter can use source tab and row for mapping; stable IDs are needed before live writes.');$('.sync-card strong').textContent='Workbook snapshot';$('.sync-card small').textContent='No live sync';
$('.notification-button').remove();$('.profile .icon-button').remove();
fetch('workbook.json').then(r=>{if(!r.ok)throw Error();return r.json()}).then(data=>{db=data;const hash=decodeURIComponent(location.hash.slice(1));if(db[hash])tab=hash;render()}).catch(()=>{$('#page').textContent='Workbook snapshot could not load. Please reload.'});
